// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rovers.API.Data;

#nullable disable

namespace Rovers.API.Migrations
{
    [DbContext(typeof(RoversDbContext))]
    [Migration("20260521124029_ExpandPerformanceAnalyticsSchema")]
    partial class ExpandPerformanceAnalyticsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rovers.API.Models.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<bool?>("IsPositive")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "is_positive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatField")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasAnnotation("Relational:JsonPropertyName", "stat_field");

                    b.HasKey("Id");

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("Rovers.API.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Competition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<DateTime?>("MatchDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "match_date");

                    b.Property<string>("MatchTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasAnnotation("Relational:JsonPropertyName", "match_title");

                    b.Property<int>("OpponentId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "opponent_id");

                    b.Property<int?>("OpponentScore")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "opponent_score");

                    b.Property<string>("Result")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("RoversScore")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "rovers_score");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "season_id");

                    b.Property<string>("Venue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OpponentId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Rovers.API.Models.MatchEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "event_type");

                    b.Property<int?>("EventTypeId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "event_type_id");

                    b.Property<int?>("MatchId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "match_id");

                    b.Property<string>("MatchTime")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasAnnotation("Relational:JsonPropertyName", "match_time");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "player_id");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "player_name");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchEvents");
                });

            modelBuilder.Entity("Rovers.API.Models.Opponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Opponents");
                });

            modelBuilder.Entity("Rovers.API.Models.PlayerMatchStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Carries")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<double?>("HandErr")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "hand_err");

                    b.Property<double?>("KpiScore")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "kpi_score");

                    b.Property<double?>("LineBreaks")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "line_breaks");

                    b.Property<int>("MatchId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "match_id");

                    b.Property<double?>("Missed")
                        .HasColumnType("float");

                    b.Property<double?>("Offloads")
                        .HasColumnType("float");

                    b.Property<double?>("PenC")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "pen_c");

                    b.Property<double?>("PerformancePct")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "performance_pct");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "player_id");

                    b.Property<int>("Pos")
                        .HasColumnType("int");

                    b.Property<double?>("RucksClean")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "rucks_clean");

                    b.Property<double?>("TackAss")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "tack_ass");

                    b.Property<double?>("TackMade")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "tack_made");

                    b.Property<double?>("Target")
                        .HasColumnType("float");

                    b.Property<double?>("TimePlay")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "time_play");

                    b.Property<double?>("TurnOvers")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "turn_overs");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerMatchStats");
                });

            modelBuilder.Entity("Rovers.API.Models.PlayerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "is_active");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "jersey_number");

                    b.Property<string>("PositionGroup")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasAnnotation("Relational:JsonPropertyName", "position_group");

                    b.Property<string>("PrimaryPosition")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "primary_position");

                    b.Property<string>("ShortName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasAnnotation("Relational:JsonPropertyName", "short_name");

                    b.HasKey("Id");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("Rovers.API.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Rovers.API.Models.TeamKpi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ActualValue")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "actual_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<int>("MatchId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "match_id");

                    b.Property<bool?>("MetTarget")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "met_target");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "metric_name");

                    b.Property<double?>("TargetValue")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "target_value");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("TeamKpis");
                });

            modelBuilder.Entity("Rovers.API.Models.Match", b =>
                {
                    b.HasOne("Rovers.API.Models.Opponent", "Opponent")
                        .WithMany("Matches")
                        .HasForeignKey("OpponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rovers.API.Models.Season", "Season")
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opponent");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Rovers.API.Models.MatchEvent", b =>
                {
                    b.HasOne("Rovers.API.Models.EventType", "EventTypeNavigation")
                        .WithMany()
                        .HasForeignKey("EventTypeId");

                    b.HasOne("Rovers.API.Models.Match", "Match")
                        .WithMany("Events")
                        .HasForeignKey("MatchId");

                    b.HasOne("Rovers.API.Models.PlayerProfile", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("EventTypeNavigation");

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Rovers.API.Models.PlayerMatchStat", b =>
                {
                    b.HasOne("Rovers.API.Models.Match", "Match")
                        .WithMany("PlayerStats")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rovers.API.Models.PlayerProfile", "Player")
                        .WithMany("MatchStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Rovers.API.Models.TeamKpi", b =>
                {
                    b.HasOne("Rovers.API.Models.Match", "Match")
                        .WithMany("TeamKpis")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Rovers.API.Models.Match", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("PlayerStats");

                    b.Navigation("TeamKpis");
                });

            modelBuilder.Entity("Rovers.API.Models.Opponent", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Rovers.API.Models.PlayerProfile", b =>
                {
                    b.Navigation("MatchStats");
                });

            modelBuilder.Entity("Rovers.API.Models.Season", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
